taskkill /im G1.exe -F
taskkill /im G2.exe -F
taskkill /im G1.exe -F
taskkill /im G2.exe -F
taskkill /im G1.exe -F
taskkill /im G2.exe -F
taskkill /im G1.exe -F
taskkill /im G2.exe -F
taskkill /im G1.exe -F
taskkill /im G2.exe -F
taskkill /im G1.exe -F
taskkill /im G2.exe -F
taskkill /im G1.exe -F
taskkill /im G2.exe -F
taskkill /im p1.exe -F